# syntax = docker/dockerfile:experimental
#
# Build stage
#
FROM maven:3.6.0-jdk-8-slim AS outsidebuild
WORKDIR /app
COPY ./target/gateway-0.0.1-SNAPSHOT.jar /usr/local/lib/cab_gateway.jar
EXPOSE 9001
ENTRYPOINT ["java","-jar","/usr/local/lib/cab_gateway.jar"]