# syntax = docker/dockerfile:1.0-experimental
#
# Build stage
#
FROM maven:3.6.0-jdk-8-slim AS outsidebuild
WORKDIR /app
COPY ./target/cab-0.0.1-SNAPSHOT.jar /usr/local/lib/cab.jar
EXPOSE 9080
ENTRYPOINT ["java","-jar","/usr/local/lib/cab.jar"]